spring.application.name=tank-solar-heater-be

spring.datasource.url=jdbc:postgresql://localhost:5432/TankSolarHeater
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# Tự động cập nhật cấu trúc bảng từ Entity Java vào DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true